apps/product/urls.py
from django.urls import path
from .views import ProductListView, product_search, product_list_ajax


app_name = 'product-urls'
urlpatterns = [
    path('', ProductListView.as_view(), name='product-list'),
    path('products/search/', product_search, name='product-search'),
    path('product-list-ajax/', product_list_ajax, name='product_list_ajax'),
]

apps/user/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from .views import login_view, logout_view, signup_view, view_edit_profile_view


app_name = 'user-urls'
urlpatterns = [
  
    path('user/signup/', signup_view, name='signup'),
    path('user/login/', login_view, name='login'),
    path('user/profile/', view_edit_profile_view, name='profile'),
    path('user/logout/', logout_view, name='logout'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/wishlist/urls.py
# urls.py
from django.urls import path
from . import views 

app_name='wishlist-urls'
urlpatterns = [
    path('wishlist/', views.wishlist_view, name='wishlist'), 
    path('wishlist/add/<int:product_id>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('wishlist/remove/<int:product_id>/', views.remove_from_wishlist, name='remove_from_wishlist'),
    path('wishlist/total/', views.get_wishlist_total, name='get_wishlist_total'),
    path('wishlist/save/', views.save_wishlist, name='save_wishlist'),
    path("wishlist/download/", views.download_wishlist_pdf, name="download_wishlist"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include




urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('apps.main.urls', namespace='main-urls')),
    path("", include('apps.product.urls', namespace='product-urls')),
    path("", include('apps.user.urls', namespace='user-urls')),
    path("", include('apps.wishlist.urls', namespace='wishlist-urls')),
]

apps/product/models.py
from django.db import models
from apps.core.constraints import STORE_NAMES
# Create your models here.


class Product(models.Model):
    store = models.CharField(max_length=30, choices=STORE_NAMES)
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=150, null=True, blank=True)
    price = models.FloatField()
    currency = models.CharField(max_length=5)
    category = models.CharField(max_length=100, null=True, blank=True)
    image = models.URLField(max_length=255)
    link = models.URLField(max_length=255)
    id_tag = models.CharField(max_length=50, null=True, blank=True) # CharField (encrypt decrypt)

    def __str__(self) -> str:
        return f"Store: {self.store}, Product: {self.name}, Price: {self.price}{self.currency}"

apps/product/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.views.generic import ListView, DetailView
from django.db.models import Q

from .models import Product


# Create your views here.


class ProductListView(ListView):
    model = Product
    template_name = 'main.html'
    context_object_name = 'products'
    paginate_by = 12


    def get_queryset(self):
        queryset = super().get_queryset()
        product_name = self.request.GET.get('product_name', '')
        category = self.request.GET.get('category', '')

        # Use regex for advanced filtering by product name and category
        if product_name and category:
            queryset = queryset.filter(
                Q(name__iregex=r'\y{}\y'.format(product_name)) & 
                Q(category__iregex=r'\y{}\y'.format(category))
            ).order_by('price')
        elif product_name:
            queryset = queryset.filter(Q(name__iregex=r'\y{}\y'.format(product_name))).order_by('price')
        elif category:
            queryset = queryset.filter(Q(category__iregex=r'\y{}\y'.format(category))).order_by('price')


        return queryset

    def get_context_data(self, **kwargs):
            # Get the default context data from the parent class
            context = super().get_context_data(**kwargs)

            # Fetch distinct categories from the Product model
            context['categories'] = Product.objects.values_list('category', flat=True).distinct()


            # Add pagination-related context
            context['is_paginated'] = context['paginator'].num_pages > 1 if 'paginator' in context else False
            context['page_obj'] = context.get('page_obj')
            context['paginator'] = context.get('paginator')

            # Pass the current search query to the context
            context['search_query'] = self.request.GET.get('product_name', '')
            context['search_category'] = self.request.GET.get('category', '')

            return context
        

# AJAX-based product list view
def product_list_ajax(request):
    product_name = request.GET.get('product_name', '')
    category = request.GET.get('category', '')

    products = Product.objects.filter(
        Q(name__icontains=product_name) & Q(category__icontains=category)
    ).order_by('price')

    products_data = [
        {
            'name': product.name,
            'price': product.price,
            'store': product.store,
            'description': product.description,
            'image': product.image.url,
            'link': product.link,
        }
        for product in products
    ]

    return JsonResponse({'products': products_data})


def product_search(request):
    if 'q' in request.GET:
        query = request.GET['q']
        products = Product.objects.filter(name__icontains=query)[:10]  # Limit results for autocomplete
        product_names = [product.name for product in products]
        return JsonResponse(product_names, safe=False)
    return JsonResponse([], safe=False)

apps/product/templates/prosffer.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>prosffer</title>
    <link rel="shortcut icon" href="{% static 'images/favcon/favicon-prosffer.ico' %}" type="image/x-icon">

    <!-- External CSS file -->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
  </head>
  <body>
    <script>
      const userIsLoggedIn = {{ user.is_authenticated|yesno:"true,false" }};
      const saveWishlistUrl = "{% url 'wishlist-urls:save_wishlist' %}";
      var wishlistUrl = '{% url 'wishlist-urls:wishlist' %}';
    </script>
    <!-- Header Section -->
    <header>
      <div class="logo">
        <a href="{% url 'product-urls:product-list' %}">
            <img
              src="{% static 'images/logo/prosffer_logo_tags.svg' %}"
              alt="Logo"
            />
        </a>
      </div>


      <!-- Search Section -->
      <div class="search-container">
        <form method="GET" action="">
          <input
            type="text"
            id="product-search"
            name="product_name"
            placeholder="Compare Product Prices"
            value="{{ request.GET.product_name }}"
            autocomplete="off"
          />
          <select id="category-select" name="category">
            <option value="">Select Category</option>
              {% for cat in categories %}
            <option value="{{ cat }}" {% if request.GET.category == cat %}selected{% endif %}>
              {{ cat }}
            </option>
              {% endfor %}
          </select>
          <button type="submit">
            <img
              src="{% static 'images/icons/looper-white.svg' %}"
              alt="Search"
            />
          </button>
        </form>
        <div id="suggestions" class="suggestions">
          {% for suggestion in suggestions %}
          <p>{{ suggestion }}</p>
          {% endfor %}
        </div> 
      </div>

          <div class="user-menu">
              <div class="user_dropdown">
                  <button id="user-icon-btn" class="user-icon-btn">
                      {% if request.user.is_authenticated %}
                          {% if request.user.consumer.profile_image %}
                              <img src="{{ request.user.consumer.profile_image.url }}" alt="User Profile Picture" class="user-icon">
                          {% else %}
                              <img src="{% static 'images/icons/user_icon.svg' %}" alt="Default User Icon" class="user-icon">
                          {% endif %}
                      {% else %}
                          <img src="{% static 'images/icons/user_icon.svg' %}" alt="User Icon" class="user-icon">
                      {% endif %}
                  </button>
              </div>
          </div>

          <!-- Login Modal -->
          <div id="loginModal" class="modal">
            <div class="modal-content form-container">
              <span class="close" id="closeLogin">&times;</span>
              <h2>Login</h2>
          
              <div class="messages"></div>

              <form method="POST" action="{% url 'user-urls:login' %}">
                {% csrf_token %}
                <label for="username">Username:</label>
                <input type="text" name="username" id="username" required autocomplete="off">
          
                <label for="password">Password:</label>
                <input type="password" name="password" id="password" required autocomplete="off">
          
                <button type="submit">Login</button>
              </form>
          
              <p>Don't have an account? <a href="#" id="showSignUp">Sign up here</a></p>
            </div>
          </div>

          <!-- Signup Modal -->
          <div id="signupModal" class="modal">
            <div class="modal-content">
                <span class="close" id="closeSignup">&times;</span>
                <div class="form-container">
                    <h2>Sign Up</h2>

                    <!-- Display messages if any -->
                    <div class="messages"></div>

                    <form method="POST" action="{% url 'user-urls:signup' %}">
                        {% csrf_token %}
                
                        <label for="username">Username</label>
                        <input type="text" id="username" name="username" required autocomplete="off">

                        <label for="email">Email</label>
                        <input type="email" id="email" name="email" required autocomplete="off">

                        <label for="password1">Password</label>
                        <input type="password" id="password1" name="password1" required autocomplete="off">

                        <label for="password2">Confirm Password</label>
                        <input type="password" id="password2" name="password2" required >

                        <button type="submit">Sign Up</button>
                        <p>Already have an account? <a href="#" id="showLogin">Login</a></p>
                    </form>
                </div>
            </div>
          </div>

          <!-- User Dropdown Menu -->
          <div class="user-dropdown-content" id="user-dropdown-content">
            {% if user.is_authenticated %}
              <p>Hi, {{ user.first_name }}</p> <!-- Display the user's first name -->
              <hr class="divider">
              <a href="{% url 'user-urls:profile' %}">Profile</a>
              <a href="{% url 'user-urls:logout' %}">Logout</a>
            {% else %}
              <a href="#" id="loginBtn">Login</a> <!-- Keep as an anchor for the modal pop-up -->
              <a href="#" id="signupBtn">Sign Up</a> <!-- Trigger Sign Up modal -->
            {% endif %}
          </div>
        </div>


        <!-- Wishlist Dropdown -->
        <div class="wishlist-dropdown">
          <button id="wishlist-btn" class="wishlist-btn">
            <img
              src="{% static 'images/icons/wishlist_icon.svg' %}"
              alt="Wishlist Icon"
              class="wishlist-icon"
            />
            <span id="total-price">0.00 €</span>
            <span id="wishlist-count" style="display: none;">0</span>
            <!-- Display total price -->
          </button>
          <div class="wishlist-content" id="wishlist-content">
            <div class="wishlist-header">
                <h4>Wishlist</h4>
            </div>
        
            <div class="wishlist-body" id="wishlist-body">
                <table id="wishlist-items">
                    <thead>
                        <tr>
                            <th>Image</th>
                            <th>Store</th>
                            <th>Product</th>
                            <th>Quantity</th>
                            <th>Price</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody id="wishlist-items-container">
                        <!-- Wishlist items will be dynamically added here -->
                    </tbody>
                </table>
            </div>
        
            <div class="wishlist-footer">
                <!-- Total Price section -->
                <div class="total-price-section">
                    <strong>Total Price:</strong> <span id="total-price-display">0.00 €</span>
                </div>
                
                <!-- Buttons at the bottom, horizontally aligned -->
                <!-- New wrapper around the buttons -->
                <div class="wishlist-buttons-wrapper">
                  <div class="wishlist-buttons">
                      <button id="save-wishlist-btn">Save to Wishlist</button>
                      <button id="goto-wishlist-btn">Go to Wishlist</button>
                  </div>
                </div>
            </div>
          </div>
    </header>


<!-- Product Listing Section -->
<div id="product-list">
    {% if products %}
    <div class="slogan">
      <h2>Proactively Surf for <span class="highlight">Best</span> Offers</h2>
    </div>
    <div class="product-comparison">
      {% for product in products %}
      <div class="product-card">
        <!-- Product Name in Header -->
        <h3>{{ product.name }}</h3>
      
        <!-- Product Details in Body -->
        <div class="product-details">
            <img src="{{ product.image }}" alt="{{ product.name }}" class="product-thumbnail" />
            <div class="details-scrollable">
                <span class="store-name">{{ product.store }}</span>
                <span class="product-desc">{{ product.description }}</span>
                <span class="price">{{ product.price }} {{ product.currency }}</span>
            </div>
        </div>
      
        <!-- Footer Section with Buttons -->
        <div class="product-footer">
            <a href="{{ product.link }}" target="_blank" class="view-button">
                <img src="{% static 'images/icons/view_icon.svg' %}" alt="View Icon" />
                <span class="tooltip-text">See in Store</span>
            </a>
            <button
                class="add-to-wishlist"
                data-product-id="{{ product.id }}"
                data-store-name="{{ product.store }}"
                data-product-name="{{ product.name }}"
                data-product-price="{{ product.price }}"
                data-product-currency="{{ product.currency }}"
                data-product-image="{{ product.image }}"
            >
                <img src="{% static 'images/icons/add_icon.svg' %}" alt="Add Icon" />
                <span class="tooltip-text">Add to Wishlist</span>
            </button>
        </div>
      </div>
        {% endfor %}
      </div>
      {% if is_paginated %}
        <div class="pagination">
          <span class="step-links">
            {% if page_obj.has_previous %}
              <a href="?page=1&category={{ request.GET.category|urlencode }}&product_name={{ request.GET.product_name|urlencode }}">
                <img class="pagination-icon" src="{% static 'images/icons/first_icon.svg' %}" alt="First">
              </a>
              <a href="?page={{ page_obj.previous_page_number }}&category={{ request.GET.category|urlencode }}&product_name={{ request.GET.product_name|urlencode }}">
                <img class="pagination-icon" src="{% static 'images/icons/previous_icon.svg' %}" alt="Previous">
              </a>
            {% endif %}
            
            <span class="current">
              Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
            </span>

            {% if page_obj.has_next %}
              <a href="?page={{ page_obj.next_page_number }}&category={{ request.GET.category|urlencode }}&product_name={{ request.GET.product_name|urlencode }}">
                <img class="pagination-icon" src="{% static 'images/icons/next_icon.svg' %}" alt="Next">
              </a>
              <a href="?page={{ page_obj.paginator.num_pages }}&category={{ request.GET.category|urlencode }}&product_name={{ request.GET.product_name|urlencode }}">
                <img class="pagination-icon" src="{% static 'images/icons/last_icon.svg' %}" alt="Last">
              </a>
            {% endif %}
          </span>
        </div>
      {% endif %}
    {% else %}
    <p class="no-products"></p>
    {% endif %}
</div>


    <!-- External JS file -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{% static 'js/suggestions_functions.js' %}"></script>
    <script src="{% static 'js/user_wishlist_button_functions.js' %}"></script>
    <script src="{% static 'js/wishlist_quickview_functions.js' %}"></script>
    <script src="{% static 'js/login_signup.js' %}"></script>

    <footer>
      <p>&copy; 2024 Prosffer made with ♡</p>
    </footer>
  </body>
</html>